#Challenge - Joining on multiple tables
#Write SQL queries to perform the following tasks using the Sakila database:
USE sakila;


# 1. List the number of films per category
SELECT * FROM category;
SELECT * FROM film_category;

SELECT c.name, COUNT(fc.film_id) AS number_of_films_in_category
FROM category AS c
LEFT JOIN film_category AS fc
USING (category_id)
GROUP BY c.name;

# 2. Retrieve the store ID, city, and country for each store.
SELECT * FROM store;

SELECT s.store_id, ci.city, co.country
FROM store as s
INNER JOIN address as a
USING(address_id)
INNER JOIN city as ci
USING(city_id)
INNER JOIN country as co
USING(country_id);

# 3. Calculate the total revenue generated by each store in dollars.

SELECT s.store_id, CONCAT('$', FORMAT(SUM(p.amount), 2)) as revenue
FROM store as s
INNER JOIN inventory as i
USING(store_id)
INNER JOIN rental as r
USING(inventory_id)
INNER JOIN payment as p
USING(rental_id)
GROUP BY s.store_id;

# 4. Determine the average running time of films for each category.
SELECT c.name, AVG(f.length) as avg_duration
FROM category as c
INNER JOIN film_category as fc
USING(category_id)
INNER JOIN film as f
USING(film_id)
GROUP BY c.name;


#Bonus:
# 5. Identify the film categories with the longest average running time.
SELECT c.name, AVG(f.length) as avg_duration
FROM category as c
INNER JOIN film_category as fc
USING(category_id)
INNER JOIN film as f
USING(film_id)
GROUP BY c.name
ORDER BY avg_duration DESC;


# 6. Display the top 10 most frequently rented movies in descending order.



# 7. Determine if "Academy Dinosaur" can be rented from Store 1.
SELECT s.store_id, f.title
FROM store as s
INNER JOIN inventory as i
USING(store_id)
INNER JOIN film as f
USING(film_id)
WHERE title = "Academy Dinosaur";
	###ANSWER: yes


# 8. Provide a list of all distinct film titles, along with their availability status in the inventory.
	#Include a column indicating whether each title is 'Available' or 'NOT available.' 
    #Note that there are 42 titles that are not in the inventory, 
    #and this information can be obtained using a CASE statement combined with IFNULL."